name: Slack Notification Demo

on: push

env:
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}   
  
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: '#EB1C1C'
        SLACK_MESSAGE: ':bomb: ${{ github.job }} job has been executed with ${{ job.status }} status, thank you ❌'
          
          
  slackNotification2:
    name: Slack Notification2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: '#008000'
        SLACK_MESSAGE: '🍺 ${{ github.job }} job has been executed with ${{ job.status }} status, thank you :trophy:'
