name: Slack Notification Demo

on: push

env:
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}   
  
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_MESSAGE: 'Updated failed notification'
        color: failed
          
          
  slackNotification2:
    name: Slack Notification2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@master 
      env:
        SLACK_MESSAGE: '${{ github.job }} job has been executed with ${{ job.status }} status, thank you - latest'    
