# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: echo context

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: print name and status
        run: echo ${{ github.job }} " and " ${{ job.status }} 
      - name: slack notification
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello, World!"}' 
          https://hooks.slack.com/services/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
