# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: echo context

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: print name and status
        run: echo ${{ github.job }} " and " ${{ job.status }} 
      - name: slack notification
        # Send notification to slack
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"${{ github.job }} job execution is completed with ${{ job.status }} status, thank you"}' ${{ secrets.SLACK_WEBHOOK }}
