# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Manually triggered workflow
on:
  schedule:
    #This workflow schedule to run the job at 9:30PM on every day-of-week from Monday through Friday
    - cron: "0 16 * * 1-5"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      run: echo "Test"
    - name: print job context
      run: echo "$GITHUB_CONTEXT"
    - name: print job name and status
      run: echo job.container.id " and " job.status
